from app.core.config import settings


def gateway_summary() -> dict:
    return {
        "auth_service": settings.auth_service_base_url,
        "signal_service": settings.signal_service_base_url,
        "portfolio_service": settings.portfolio_service_base_url,
        "statistics_service": settings.statistics_service_base_url,
        "user_propagation_header": "X-User-ID",
        "authenticated_routes": [
            "/auth/register",
            "/auth/login",
            "/auth/refresh",
            "/me",
            "/dashboard",
            "/signals",
            "/feed",
            "/strategies",
            "/settings",
            "/orders",
            "/gateway/me",
            "/gateway/dashboard",
            "/gateway/signals",
            "/gateway/feed",
            "/gateway/memory/record",
            "/gateway/memory/search",
            "/gateway/strategies/active",
            "/gateway/strategies",
            "/gateway/strategies/{strategy_id}/status",
            "/gateway/orders",
            "/gateway/settings",
            "/gateway/settings/credentials",
            "/gateway/settings/risk",
            "/admin/users",
            "/admin/users/{user_id}/roles",
            "/admin/system/health",
            "/admin/system/events",
        ],
        "websocket_bridge": "/ws?token=<jwt>",
        "realtime_topics": [
            "order.filled.*",
            "signal.threshold.crossed.*",
            "risk.triggered.*",
            "agent.*.action",
            "portfolio.updated",
            "statistics.updated",
        ],
    }
