"""Public contracts for the Quant Platform open-core project."""

from .backtest import (
    BacktestConfig,
    BacktestPoint,
    BacktestResult,
    BacktestRunner,
    BacktestSummary,
)
from .contracts import (
    AlphaPlugin,
    BatchAlphaPlugin,
    MarketBar,
    OrderIntent,
    PositionTarget,
    RiskDecision,
    Signal,
)
from .finance import (
    AfterTaxSummary,
    CostBasisMethod,
    ExecutionFill,
    ExecutionIntent,
    ExecutionOrder,
    ExecutionOrderType,
    ExecutionRealityProfile,
    FinancialLedger,
    FinancialLedgerEntry,
    FinancialLedgerSummary,
    LedgerEntryKind,
    LiquidityRole,
    OrderSide,
    OrderState,
    TaxableEvent,
    TaxableEventKind,
    TaxConfidence,
    TaxEstimate,
    TaxLot,
    TaxProfile,
    apply_tax_estimate,
    summarize_financial_ledger,
)
from .registry import PluginRegistry

__all__ = [
    "AfterTaxSummary",
    "AlphaPlugin",
    "BacktestConfig",
    "BacktestPoint",
    "BacktestResult",
    "BacktestRunner",
    "BacktestSummary",
    "BatchAlphaPlugin",
    "CostBasisMethod",
    "ExecutionFill",
    "ExecutionIntent",
    "ExecutionOrder",
    "ExecutionOrderType",
    "ExecutionRealityProfile",
    "FinancialLedger",
    "FinancialLedgerEntry",
    "FinancialLedgerSummary",
    "LedgerEntryKind",
    "LiquidityRole",
    "MarketBar",
    "OrderIntent",
    "OrderSide",
    "OrderState",
    "PluginRegistry",
    "PositionTarget",
    "RiskDecision",
    "Signal",
    "TaxConfidence",
    "TaxEstimate",
    "TaxLot",
    "TaxProfile",
    "TaxableEvent",
    "TaxableEventKind",
    "apply_tax_estimate",
    "summarize_financial_ledger",
]
