apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quant

resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - configmap.yaml
  - timescaledb.yaml
  - redis.yaml
  - nats.yaml
  - market-pipeline.yaml
  - execution.yaml
  - platform.yaml
  - cronjobs.yaml

commonLabels:
  app.kubernetes.io/part-of: quant-platform
  app.kubernetes.io/managed-by: kustomize
